### ISSUE TITLE
Are you interested in discussing alternative solutions for exercises?

### ISSUE THREAD

**Issue by geomlyd** [jubnoske08/linear_algebra#2]
Hi there!

First of all, thank you for this resource! I'm brushing up on my linear algebra and the book is great, it's good to know I can go through the exercises with some indicative solutions available. I wanted to ask, are you interested in users opening issues regarding possible different solutions for exercises?

**Comment by jubnoske08** [comment]
Hi geomlyd,

Thank you for the kind words!  I think the best place for discussing alternative approaches/solutions is probably a more public venue such as stackexchange or reddit's /r/math page.  This site isn't really intended to be much more than a website hosting my own thoughts on the problems.
